name: Earth deploy
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: sudo apt install sshpass
    - name: pull and reload
      run: |
        sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd ${{secrets.DST}}; git pull;"
